jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - continue-on-error: true
      name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Setting up the system environment
      run: cp ./.github/workflows/github-action-only.jks ./app/keys.jks
    - continue-on-error: true
      name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669"
    - continue-on-error: true
      name: Build with Gradle
      run: export KEYSTORE_PASS=000000000 && export ALIAS_NAME="key0" && export ALIAS_PASS=111111111
        && export VERSION_CODE=1 && export VERSION_NAME="GITHUB-${GITHUB_SHA}" &&
        ./gradlew app:copy_language_pack && ./gradlew assembleRelease
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: telegram-sms
        path: app/build/outputs/apk/release/app-release.apk
name: Android User Build
on:
  repository_dispatch:
    types: trigger-ga___android.yml
